framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
            - vendor/twbs/bootstrap/dist
            - assets/vendor/ky
            
sensiolabs_typescript:
    source_dir: ['%kernel.project_dir%/assets/ts']