nelmio_api_doc:
    documentation:
        info:
            title: TeamtaskAPI
            description: TeamTask WebApp's API. 
            version: 1.0.0
        paths:
            /api/users/login_check:
                post:
                    operationId: postCredentialsItem
                    tags:
                        - Token
                    summary: Login to the Teamtask API.
                    requestBody:
                        description: Create a new JWT token.
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Credentials'
                    responses:
                        '204':
                            description: Authentication successfull. Store the JWT token and the refresh token in two separate cookies (BEARER and refresh_token respectively).
                        '401':
                            description: "Invalid credentials."
            /api/token/refresh:
                post:
                    tags:
                        - Token
                    summary: Refresh token mechanism.
                    parameters:
                        refresh_token:
                            in: query
                            name: refresh_token
                            description: 'Value of refresh_token' 
                            schema: 
                                type: 'string'
                    responses:
                        '204':
                            description: Refresh token found, new JWT token generated.
                        '401':
                            description: "Refresh token not found."
        tags: 
            - name: Token
            - name: Users
              description: 'Endpoints related to main actions on users (including yourself).'
            - name: Friend requests
              description: 'Endpoints related to friend requests between users.'
            - name: Friends
              description: 'Endpoints related to user friendships.'
        components:
            schemas:
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: testAPI
                        password:
                            type: string
                            default: testAPI
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - bearerAuth: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
